version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::10"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk==  # <- deine generierte ID
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://[::]:9092,CONTROLLER://[::]:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://[fd00:dead:cafe::10]:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@[fd00:dead:cafe::10]:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "[fd00:dead:cafe::10]:9092", "--list" ]  # verify kafka is operational
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - kafka-data:/var/lib/kafka/data
    entrypoint:
      - bash
      - -c
      - |
        if [ ! -f "/var/lib/kafka/data/meta.properties" ]; then
          echo "? Initializing Kafka KRaft cluster with ID $CLUSTER_ID..."
          kafka-storage format --cluster-id $CLUSTER_ID --config /etc/kafka/kafka.properties
        fi
        echo "?? Starting Kafka broker..."
        exec /etc/confluent/docker/run

  init-kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - kafka
    entrypoint: [ "sh", "/init-kafka.sh" ]
    volumes:
      - ./kafka/init/init-kafka.sh:/init-kafka.sh
    networks:
      - workshop-net

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: analytics
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::100"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  
  checkout:
    build:
      context: ./checkout
    container_name: checkout
    depends_on:
      - init-kafka
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::30"
  
  order:
    build:
      context: ./order
    container_name: order
    depends_on:
      - init-kafka
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::50"
  
  fulfillment:
    build:
      context: ./fulfillment
    container_name: fulfillment
    depends_on:
      - init-kafka
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::40"
  
  analytics:
    build:
      context: ./analytics
    container_name: analytics
    depends_on:
      - init-kafka
    networks:
      workshop-net:
        ipv6_address: "fd00:dead:cafe::20"

volumes:
  kafka-data:

networks:
  workshop-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:dead:cafe::/64"